"""add description and vitals

Revision ID: 0ed3fab287f2
Revises: df58354443d8
Create Date: 2026-06-08 16:23:21.150511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ed3fab287f2'
down_revision: Union[str, None] = 'df58354443d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('allergy', sa.Column('descripcion', sa.String(), nullable=True))
    op.add_column('clinical_evolution', sa.Column('peso_kg', sa.Float(), nullable=True))
    op.add_column('clinical_evolution', sa.Column('talla_cm', sa.Float(), nullable=True))
    op.add_column('clinical_evolution', sa.Column('perimetro_cefalico_cm', sa.Float(), nullable=True))
    op.add_column('clinical_evolution', sa.Column('tension_arterial', sa.String(), nullable=True))
    op.add_column('lab_result', sa.Column('descripcion', sa.String(), nullable=True))
    op.add_column('medication', sa.Column('descripcion', sa.String(), nullable=True))
    op.add_column('procedure', sa.Column('descripcion', sa.String(), nullable=True))
    op.add_column('vaccine', sa.Column('descripcion', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vaccine', 'descripcion')
    op.drop_column('procedure', 'descripcion')
    op.drop_column('medication', 'descripcion')
    op.drop_column('lab_result', 'descripcion')
    op.drop_column('clinical_evolution', 'tension_arterial')
    op.drop_column('clinical_evolution', 'perimetro_cefalico_cm')
    op.drop_column('clinical_evolution', 'talla_cm')
    op.drop_column('clinical_evolution', 'peso_kg')
    op.drop_column('allergy', 'descripcion')
    # ### end Alembic commands ###
