"""Add federation_id to patient

Revision ID: 1c89552f8315
Revises: 61007e116b21
Create Date: 2026-06-10 08:35:19.208649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c89552f8315'
down_revision: Union[str, None] = '61007e116b21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient', sa.Column('federation_id', sa.String(), nullable=True))
    op.add_column('patient', sa.Column('federated_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'patient', 'user', ['federated_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'patient', type_='foreignkey')
    op.drop_column('patient', 'federated_by')
    op.drop_column('patient', 'federation_id')
    # ### end Alembic commands ###
