"""Update Vaccine foreign key to snomed_concepts_vaccine

Revision ID: 288727777656
Revises: af427a536dd2
Create Date: 2026-06-10 10:12:27.186471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '288727777656'
down_revision: Union[str, None] = 'af427a536dd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('vaccine_snomed_concept_id_fkey'), 'vaccine', type_='foreignkey')
    op.create_foreign_key(None, 'vaccine', 'snomed_concepts_vaccine', ['snomed_concept_id'], ['conceptid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vaccine', type_='foreignkey')
    op.create_foreign_key(op.f('vaccine_snomed_concept_id_fkey'), 'vaccine', 'snomed_concepts', ['snomed_concept_id'], ['conceptid'])
    # ### end Alembic commands ###
