"""Update foreign keys for procedure and lab_result

Revision ID: 300b9bb8bfb4
Revises: dea6a9ed6038
Create Date: 2026-06-12 13:21:28.647983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '300b9bb8bfb4'
down_revision: Union[str, None] = 'dea6a9ed6038'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('lab_result_snomed_concept_id_fkey'), 'lab_result', type_='foreignkey')
    op.create_foreign_key(None, 'lab_result', 'snomed_concepts_laboratory', ['snomed_concept_id'], ['conceptid'])
    op.drop_constraint(op.f('procedure_snomed_concept_id_fkey'), 'procedure', type_='foreignkey')
    op.create_foreign_key(None, 'procedure', 'snomed_concepts_procedure', ['snomed_concept_id'], ['conceptid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'procedure', type_='foreignkey')
    op.create_foreign_key(op.f('procedure_snomed_concept_id_fkey'), 'procedure', 'snomed_concepts', ['snomed_concept_id'], ['conceptid'])
    op.drop_constraint(None, 'lab_result', type_='foreignkey')
    op.create_foreign_key(op.f('lab_result_snomed_concept_id_fkey'), 'lab_result', 'snomed_concepts', ['snomed_concept_id'], ['conceptid'])
    # ### end Alembic commands ###
