"""Add edit fields to evolution

Revision ID: 3e0b8e5a929a
Revises: 0ed3fab287f2
Create Date: 2026-06-08 16:37:27.619624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e0b8e5a929a'
down_revision: Union[str, None] = '0ed3fab287f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clinical_evolution', sa.Column('is_edited', sa.Boolean(), nullable=True))
    op.add_column('clinical_evolution', sa.Column('motivo_edicion', sa.String(), nullable=True))
    op.add_column('clinical_evolution', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clinical_evolution', 'updated_at')
    op.drop_column('clinical_evolution', 'motivo_edicion')
    op.drop_column('clinical_evolution', 'is_edited')
    # ### end Alembic commands ###
