"""Add API logs and update patient model

Revision ID: 61007e116b21
Revises: a8b25308b6e0
Create Date: 2026-06-09 14:04:56.362162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61007e116b21'
down_revision: Union[str, None] = 'a8b25308b6e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient', sa.Column('apellido_materno', sa.String(), nullable=True))
    op.add_column('patient', sa.Column('telefono', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patient', 'telefono')
    op.drop_column('patient', 'apellido_materno')
    # ### end Alembic commands ###
