"""Add SnomedConceptAllergy and SnomedConceptMedication

Revision ID: 988b8ff4d597
Revises: b293307fd516
Create Date: 2026-06-10 11:37:15.702546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '988b8ff4d597'
down_revision: Union[str, None] = 'b293307fd516'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('allergy_snomed_concept_id_fkey'), 'allergy', type_='foreignkey')
    op.create_foreign_key(None, 'allergy', 'snomed_concepts_allergy', ['snomed_concept_id'], ['conceptid'])
    op.drop_constraint(op.f('medication_snomed_concept_id_fkey'), 'medication', type_='foreignkey')
    op.create_foreign_key(None, 'medication', 'snomed_concepts_medication', ['snomed_concept_id'], ['conceptid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'medication', type_='foreignkey')
    op.create_foreign_key(op.f('medication_snomed_concept_id_fkey'), 'medication', 'snomed_concepts', ['snomed_concept_id'], ['conceptid'])
    op.drop_constraint(None, 'allergy', type_='foreignkey')
    op.create_foreign_key(op.f('allergy_snomed_concept_id_fkey'), 'allergy', 'snomed_concepts', ['snomed_concept_id'], ['conceptid'])
    # ### end Alembic commands ###
