"""initial_postgres_schema

Revision ID: a8b25308b6e0
Revises: 
Create Date: 2026-06-09 10:34:47.930764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8b25308b6e0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('apellido', sa.String(), nullable=False),
    sa.Column('documento', sa.String(), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('sexo', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_documento'), 'patient', ['documento'], unique=True)
    op.create_index(op.f('ix_patient_id'), 'patient', ['id'], unique=False)
    op.create_table('snomed_concepts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conceptid', sa.String(), nullable=False),
    sa.Column('term', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_snomed_concepts_conceptid'), 'snomed_concepts', ['conceptid'], unique=True)
    op.create_index(op.f('ix_snomed_concepts_id'), 'snomed_concepts', ['id'], unique=False)
    op.create_index(op.f('ix_snomed_concepts_term'), 'snomed_concepts', ['term'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('allergy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('snomed_concept_id', sa.String(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('severidad', sa.String(), nullable=True),
    sa.Column('reaccion', sa.String(), nullable=True),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['paciente_id'], ['patient.id'], ),
    sa.ForeignKeyConstraint(['snomed_concept_id'], ['snomed_concepts.conceptid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_allergy_id'), 'allergy', ['id'], unique=False)
    op.create_table('lab_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('snomed_concept_id', sa.String(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('resultado', sa.String(), nullable=False),
    sa.Column('unidad', sa.String(), nullable=True),
    sa.Column('referencia', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['paciente_id'], ['patient.id'], ),
    sa.ForeignKeyConstraint(['snomed_concept_id'], ['snomed_concepts.conceptid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lab_result_id'), 'lab_result', ['id'], unique=False)
    op.create_table('medication',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('snomed_concept_id', sa.String(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('dosis', sa.String(), nullable=True),
    sa.Column('frecuencia', sa.String(), nullable=True),
    sa.Column('via', sa.String(), nullable=True),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['paciente_id'], ['patient.id'], ),
    sa.ForeignKeyConstraint(['snomed_concept_id'], ['snomed_concepts.conceptid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medication_id'), 'medication', ['id'], unique=False)
    op.create_table('problem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('snomed_concept_id', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('fecha_cambio', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['patient.id'], ),
    sa.ForeignKeyConstraint(['snomed_concept_id'], ['snomed_concepts.conceptid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_problem_id'), 'problem', ['id'], unique=False)
    op.create_table('procedure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('snomed_concept_id', sa.String(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('observaciones', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['paciente_id'], ['patient.id'], ),
    sa.ForeignKeyConstraint(['snomed_concept_id'], ['snomed_concepts.conceptid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_procedure_id'), 'procedure', ['id'], unique=False)
    op.create_table('vaccine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('snomed_concept_id', sa.String(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('lote', sa.String(), nullable=True),
    sa.Column('observaciones', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['paciente_id'], ['patient.id'], ),
    sa.ForeignKeyConstraint(['snomed_concept_id'], ['snomed_concepts.conceptid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vaccine_id'), 'vaccine', ['id'], unique=False)
    op.create_table('clinical_evolution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('problema_id', sa.Integer(), nullable=True),
    sa.Column('autor_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('peso_kg', sa.Float(), nullable=True),
    sa.Column('talla_cm', sa.Float(), nullable=True),
    sa.Column('perimetro_cefalico_cm', sa.Float(), nullable=True),
    sa.Column('tension_arterial', sa.String(), nullable=True),
    sa.Column('texto_clinico', sa.Text(), nullable=False),
    sa.Column('estructurado', sa.JSON(), nullable=True),
    sa.Column('is_edited', sa.Boolean(), nullable=True),
    sa.Column('motivo_edicion', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['autor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['patient.id'], ),
    sa.ForeignKeyConstraint(['problema_id'], ['problem.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinical_evolution_id'), 'clinical_evolution', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clinical_evolution_id'), table_name='clinical_evolution')
    op.drop_table('clinical_evolution')
    op.drop_index(op.f('ix_vaccine_id'), table_name='vaccine')
    op.drop_table('vaccine')
    op.drop_index(op.f('ix_procedure_id'), table_name='procedure')
    op.drop_table('procedure')
    op.drop_index(op.f('ix_problem_id'), table_name='problem')
    op.drop_table('problem')
    op.drop_index(op.f('ix_medication_id'), table_name='medication')
    op.drop_table('medication')
    op.drop_index(op.f('ix_lab_result_id'), table_name='lab_result')
    op.drop_table('lab_result')
    op.drop_index(op.f('ix_allergy_id'), table_name='allergy')
    op.drop_table('allergy')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_snomed_concepts_term'), table_name='snomed_concepts')
    op.drop_index(op.f('ix_snomed_concepts_id'), table_name='snomed_concepts')
    op.drop_index(op.f('ix_snomed_concepts_conceptid'), table_name='snomed_concepts')
    op.drop_table('snomed_concepts')
    op.drop_index(op.f('ix_patient_id'), table_name='patient')
    op.drop_index(op.f('ix_patient_documento'), table_name='patient')
    op.drop_table('patient')
    # ### end Alembic commands ###
