"""Add snomed_concepts_vaccine table

Revision ID: af427a536dd2
Revises: 1c89552f8315
Create Date: 2026-06-10 09:59:13.641136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af427a536dd2'
down_revision: Union[str, None] = '1c89552f8315'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
