"""Add problema_id to medication

Revision ID: b293307fd516
Revises: 288727777656
Create Date: 2026-06-10 11:03:40.964991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b293307fd516'
down_revision: Union[str, None] = '288727777656'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medication', sa.Column('problema_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'medication', 'problem', ['problema_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'medication', type_='foreignkey')
    op.drop_column('medication', 'problema_id')
    # ### end Alembic commands ###
