"""add patient geolocation

Revision ID: dea6a9ed6038
Revises: 988b8ff4d597
Create Date: 2026-06-11 17:00:18.347956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dea6a9ed6038'
down_revision: Union[str, None] = '988b8ff4d597'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'allergy', 'snomed_concepts_allergy', ['reaccion_snomed_id'], ['conceptid'])
    op.add_column('patient', sa.Column('latitud', sa.Float(), nullable=True))
    op.add_column('patient', sa.Column('longitud', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patient', 'longitud')
    op.drop_column('patient', 'latitud')
    op.drop_constraint(None, 'allergy', type_='foreignkey')
    # ### end Alembic commands ###
