"""Add via_snomed_id to medication and route administration table

Revision ID: ec4cffb64e18
Revises: 300b9bb8bfb4
Create Date: 2026-06-12 13:36:52.007387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec4cffb64e18'
down_revision: Union[str, None] = '300b9bb8bfb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medication', sa.Column('via_snomed_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'medication', 'snomed_concepts_medication_route_administration', ['via_snomed_id'], ['conceptid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'medication', type_='foreignkey')
    op.drop_column('medication', 'via_snomed_id')
    # ### end Alembic commands ###
